'use client';
import Link from 'next/link'; import {useMemo,useState,type ReactNode} from 'react'; import {platformRepository} from '@/services/platform-repository';
const {data:home}=platformRepository.getHome(); const {leaders,news,tournaments}=home;
export function Status({value}:{value:string}){return <span className={`platform-status ${value.toLowerCase()}`}>{value}</span>}
export function TournamentCard({tournament}:{tournament:typeof tournaments[number]}){return <article className="platform-card"><Status value={tournament.status}/><h3 className="mt-5 text-xl font-medium">{tournament.name}</h3><p className="mt-2 text-sm text-[#a7adb4]">{tournament.shortDescription}</p><Link className="platform-link mt-5 inline-block" href={`/tournaments/${tournament.id}`}>View event</Link></article>}
const Empty=({children}:{children:ReactNode})=><div className="platform-card mt-6 text-center"><p>{children}</p><p className="mt-2 text-sm text-[#a7adb4]">Published after verified platform data is available.</p></div>;
export function LeaderboardTable({title='Global leaderboard',mode='All modes'}:{title?:string;mode?:string}){const[query,setQuery]=useState('');const rows=useMemo(()=>leaders.filter(x=>x[1].toLowerCase().includes(query.toLowerCase())),[query]);return <section className="platform-card"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="platform-label">{mode} standings</p><h2 className="mt-1 text-xl font-medium">{title}</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} className="platform-input w-full sm:w-56" placeholder="Search verified players" aria-label="Search leaderboard"/></div>{rows.length?<div className="mt-5 overflow-x-auto"><table className="platform-table min-w-[720px]"><thead><tr>{['Player','Rank','Wins','Kills','Matches','Earnings'].map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div>:<div className="mt-5 rounded-lg border border-white/8 bg-black/15 p-5"><p className="text-sm text-[#f0f2f5]">No verified rankings yet.</p><p className="mt-2 text-sm leading-6 text-[#a7adb4]">Player name, rank, wins, kills, matches, and earnings appear only after database-connected player results are reviewed.</p></div>}</section>}
export function PageHero({eyebrow,title,copy,children}:{eyebrow:string;title:string;copy:string;children?:React.ReactNode}){return <section className="platform-hero"><div className="platform-orb platform-orb-one"/><div className="platform-orb platform-orb-two"/><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8 md:py-24"><p className="platform-label">{eyebrow}</p><h1 className="platform-title mt-5 max-w-4xl">{title}</h1><p className="mt-5 max-w-2xl leading-7 text-[#a7adb4]">{copy}</p>{children}</div></section>}
export function HomePage(){return <><PageHero eyebrow="MasterGaming.pk" title="Competitive rooms. Clear results." copy="A Free Fire tournament platform built around published rules, manual review, and verified standings."><div className="mt-8 flex flex-wrap gap-3"><Link href="/tournaments" className="platform-button">Explore tournaments</Link><Link href="/leaderboard" className="platform-button secondary">View leaderboard</Link></div></PageHero><main className="platform-shell py-12"><section><p className="platform-label">Tournament status</p><h2 className="platform-heading mt-2">Events appear when verified.</h2>{tournaments.length?<div className="mt-6 grid gap-4">{tournaments.map(t=><TournamentCard key={t.id} tournament={t}/>)}</div>:<Empty>No tournaments are published yet.</Empty>}</section><section className="py-16"><p className="platform-label">Leaderboard</p><h2 className="platform-heading mt-2">Results before rankings.</h2><LeaderboardTable/></section><section><p className="platform-label">Platform notes</p><h2 className="platform-heading mt-2">Guidance from the desk.</h2>{news.length?<div className="mt-6 grid gap-4 md:grid-cols-2">{news.map(([category,title])=><article key={title} className="platform-card"><p className="platform-label">{category}</p><h3 className="mt-3 text-xl font-medium">{title}</h3></article>)}</div>:<Empty>No announcements are published yet.</Empty>}</section></main></>}
export function LeaderboardPage(){const[mode,setMode]=useState('All modes');return <><PageHero eyebrow="Verified standings" title="Rankings follow completed results." copy="Player positions appear only after match results have been verified."/><main className="platform-shell py-12"><div className="mb-6 flex flex-wrap gap-2" role="tablist" aria-label="Leaderboard mode">{['All modes','BR','CS','Lone Wolf'].map(x=><button key={x} onClick={()=>setMode(x)} className={`platform-tab ${mode===x?'active':''}`} role="tab" aria-selected={mode===x}>{x}</button>)}</div><LeaderboardTable mode={mode} title={`${mode} leaderboard`}/></main></>}
export function RankingsPage(){return <><PageHero eyebrow="Season rankings" title="Every verified match has a place." copy="Rankings are published from registered players and verified results."/><main className="platform-shell py-12"><Empty>Waiting for verified match results.</Empty></main></>}
export function NewsPage(){return <><PageHero eyebrow="MasterGaming news" title="Tournament updates without the noise." copy="Official notices and result posts appear here when published."/><main className="platform-shell py-12">{news.length?<div className="grid gap-4 md:grid-cols-2">{news.map(([category,title])=><article className="platform-card" key={title}><p className="platform-label">{category}</p><h2 className="mt-3 text-xl font-medium">{title}</h2></article>)}</div>:<Empty>No announcements are published yet.</Empty>}</main></>}
export function InfoPage({title,copy,action}:{title:string;copy:string;action?:string}){return <><PageHero eyebrow="MasterGaming.pk" title={title} copy={copy}/><main className="platform-shell py-12"><section className="platform-card max-w-2xl"><p className="text-sm leading-7 text-[#a7adb4]">This page is ready for its verified platform service. It does not create accounts, payments, notifications, or administrative records.</p>{action&&<button className="platform-button mt-6">{action}</button>}</section></main></>}
