'use client';

import Link from 'next/link';
import { useState } from 'react';
import { helpFaqs, type TrustPage } from '@/data/trust';

export function LegalPage({ page }: { page: TrustPage }) { return <main className="platform-shell py-10 sm:py-14"><div className="max-w-3xl"><p className="platform-label">MasterGaming.pk policy</p><h1 className="platform-heading mt-3">{page.title}</h1><p className="mt-4 text-base leading-7 text-[#a7adb4]">{page.summary}</p></div><div className="mt-8 grid gap-4">{page.sections.map(section => <section key={section.heading} className="platform-card max-w-4xl cursor-default hover:!translate-y-0 hover:!border-[#292b31]"><h2 className="text-xl font-medium">{section.heading}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#a7adb4]">{section.body}</p></section>)}</div><aside className="mt-8 rounded-lg border border-[#a6ff43]/20 bg-[#a6ff43]/[.06] p-5 text-sm leading-6 text-[#c8ccd1]">Need help with a live request? <Link href="/help" className="platform-link">Visit support and FAQs</Link> for the right manual-review path.</aside></main>; }

export function HelpPage() { const [topic, setTopic] = useState('Tournament registration'); const [sent, setSent] = useState(false); return <main className="platform-shell py-10 sm:py-14"><div className="max-w-3xl"><p className="platform-label">Support center</p><h1 className="platform-heading mt-3">Get the right help path.</h1><p className="mt-4 leading-7 text-[#a7adb4]">Tournament, account, and finance records are reviewed manually by the desk. A request is not treated as received or resolved until a verified support service is connected.</p></div><section className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-3">{helpFaqs.map(([question, answer]) => <details key={question} className="platform-card cursor-default hover:!translate-y-0 hover:!border-[#292b31]"><summary className="cursor-pointer font-medium text-[#f0f2f5]">{question}</summary><p className="mt-3 text-sm leading-6 text-[#a7adb4]">{answer}</p></details>)}</div><form className="platform-card grid gap-4" onSubmit={event => { event.preventDefault(); setSent(true); }}><div><p className="platform-label">Report an issue</p><h2 className="mt-2 text-xl font-medium">Prepare a support request</h2><p className="mt-2 text-sm leading-6 text-[#a7adb4]">Include the information the desk will need once secure request delivery is available.</p></div><label className="field">Support topic<select value={topic} onChange={event => setTopic(event.target.value)} name="topic"><option>Tournament registration</option><option>Account or team</option><option>Payment proof</option><option>Rewards or credits</option><option>Withdrawal request</option><option>Admin review delay</option></select></label><label className="field">Email<input required type="email" name="email" placeholder="you@example.com" /></label><label className="field">Request or record reference<input name="reference" placeholder="Optional record ID" /></label><label className="field">What happened?<textarea required name="message" minLength={10} placeholder="Include the tournament, request, or issue details" /></label><button className="platform-button" type="submit">Prepare support request</button>{sent && <p role="status" className="rounded-md border border-[#e7b96a]/25 bg-[#e7b96a]/10 p-3 text-sm leading-6 text-[#f2d39a]">This request has not been sent or stored. Secure support delivery is not connected yet.</p>}</form></section></main>; }
