'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { achievementDefinitions, calculateBrTotal, competitiveRules, games, internalRanks, modes } from '@/data/competitive-system';
import { adminActivity, adminIdentity, adminNav, adminRows, adminStats } from '@/data/admin';
import { platformCommands } from '@/services/platform-repository';
import { authAdapter, type AuthSession } from '@/services/auth-adapter';
import { TournamentForm as ConnectedTournamentForm, TournamentList } from '@/components/admin/TournamentManagement';
import { FinanceManagement } from '@/components/admin/FinanceManagement';
import { MatchManagement } from '@/components/admin/MatchManagement';

const path = (name: string) => name === 'Dashboard' ? '/admin-panel' : `/admin-panel/${name.toLowerCase().replaceAll(' ', '-')}`;
const systems = ['Games', 'Modes', 'Rules', 'Scoring Systems', 'Tournament Formats', 'Rank Systems', 'Achievements'];

function RestrictedAdminAccess({ state }: { state: 'checking' | 'signed-out' | 'forbidden' }) {
  const content = state === 'checking'
    ? { title: 'Checking account access', copy: 'Confirming whether this browser has an authenticated admin account.' }
    : state === 'forbidden'
      ? { title: 'Admin permission required', copy: 'Your authenticated account has the Player role. Player accounts cannot access MasterGaming Control.' }
      : { title: 'Admin sign-in required', copy: 'MasterGaming Control is available only to authenticated Admin accounts. Sign in with the account assigned by the platform owner.' };
  return <main className="mx-auto flex min-h-dvh max-w-2xl items-center px-5 py-10"><section className="w-full rounded-xl border border-[#e7b96a]/30 bg-[#181a1f] p-6 shadow-[0_20px_50px_rgba(0,0,0,.28)] sm:p-8"><p className="platform-label">Restricted administration</p><h1 className="mt-3 text-3xl font-medium text-[#f0f2f5]">{content.title}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-[#a7adb4]">{content.copy}</p><div className="mt-7 rounded-lg border border-white/8 bg-black/15 p-4 text-sm leading-6 text-[#c8ccd1]">Admin access is tied to authenticated account identity and assigned permissions, not a display name, browser state, or direct URL. The platform owner account follows the same verification rule.</div>{state !== 'checking' && <div className="mt-7 flex flex-wrap gap-3"><Link href="/login" className="platform-button">Player sign-in</Link><Link href="/" className="platform-button secondary">Return to public site</Link></div>}</section></main>;
}

function Sidebar({ mobile = false, close }: { mobile?: boolean; close?: () => void }) { const pathname = usePathname(); return <aside className={mobile ? 'fixed right-0 top-0 z-40 h-dvh w-[min(320px,88vw)] overflow-y-auto border-l border-white/8 bg-[#15171b] p-5 lg:hidden' : 'hidden w-60 shrink-0 border-r border-white/8 bg-[#15171b] p-5 lg:block'}><div className="flex items-center justify-between"><Link href="/" className="text-sm text-[#a7adb4]">Public site</Link>{mobile && <button onClick={close} aria-label="Close admin navigation">×</button>}</div><p className="mt-7 text-lg font-medium">MasterGaming <span className="text-[#a6ff43]">Control</span></p><p className="mt-1 text-xs leading-5 text-[#9ba1a8]">Actions require an authenticated Admin account.</p><nav className="mt-7 grid gap-1" aria-label="Admin navigation">{adminNav.map(item => { const href = path(item); return <Link key={item} href={href} onClick={close} className={`rounded-md px-3 py-2.5 text-sm ${pathname === href ? 'bg-[#a6ff43]/12 text-[#c6ff91]' : 'text-[#a7adb4] hover:bg-white/5'}`}>{item}</Link>; })}</nav></aside>; }

function Table({ type }: { type: keyof typeof adminRows }) { const [query, setQuery] = useState(''); const rows = useMemo(() => adminRows[type].filter(row => row.join(' ').toLowerCase().includes(query.toLowerCase())), [type, query]); return <><input aria-label={`Search ${type}`} className="platform-input mt-6 w-full" value={query} onChange={event => setQuery(event.target.value)} placeholder={`Search ${type}`} />{rows.length ? <div className="mt-5 overflow-x-auto rounded-lg border border-white/8"><table className="min-w-[760px] w-full text-left text-sm"><thead><tr>{['Record', 'Details', 'Status', 'Updated'].map(title => <th className="border-b border-white/8 px-4 py-3 text-xs font-medium uppercase text-[#9ba1a8]" key={title}>{title}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}-${index}`}>{row.slice(0, 4).map((cell, cellIndex) => <td className="border-b border-white/8 px-4 py-3" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div> : <section className="platform-card mt-5 text-center"><p className="font-medium">No records are available for this view.</p><p className="mt-2 text-sm leading-6 text-[#a7adb4]">No verified records have been supplied here. This can mean there are currently no approved records, or that the connected backend has not made this data available yet.</p></section>}</>; }

function Dashboard() { return <><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-medium">Tournament desk</h1><p className="mt-2 text-sm text-[#a7adb4]">Operational figures appear only after verified platform data is connected.</p></div><Link href="/admin-panel/tournaments/create" className="platform-button">Create tournament</Link></div><section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{adminStats.map(([label, value]) => <article key={label} className="rounded-lg border border-white/8 bg-[#1a1c21] p-4"><p className="text-xs text-[#9ba1a8]">{label}</p><p className="mt-2 text-2xl font-medium">{value}</p></article>)}</section><section className="platform-card mt-6"><h2 className="font-medium">Operational workflow</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[['Tournaments', 'Set mode, format, schedule, fees, prizes, and slots.'], ['Rooms', 'Set room ID, password, match time, and unlock timing.'], ['Results', 'Enter verified placements and kills before publishing points.'], ['Finance', 'Review deposits and withdrawals manually before balance updates.']].map(([title, copy]) => <div key={title} className="rounded-lg border border-white/8 bg-black/15 p-4"><p className="text-sm font-medium">{title}</p><p className="mt-2 text-sm leading-6 text-[#a7adb4]">{copy}</p></div>)}</div></section><section className="platform-card mt-6"><h2 className="font-medium">Recent activity</h2>{adminActivity.length ? <div className="mt-4">{adminActivity.map(item => <p key={item}>{item}</p>)}</div> : <p className="mt-3 text-sm text-[#a7adb4]">No verified operational activity yet.</p>}</section></>; }

function TournamentForm() { const [mode, setMode] = useState('br'); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); const result = await platformCommands.saveTournament(); setLoading(false); setMessage(result.message); }; return <form className="platform-card mt-6 grid gap-4 lg:grid-cols-2" onSubmit={submit}><label className="field">Tournament name<input required name="name" /></label><label className="field">Game<select name="game" defaultValue="free-fire">{games.map(game => <option key={game.id} value={game.id}>{game.name}</option>)}</select></label><label className="field">Game mode<select name="mode" value={mode} onChange={event => setMode(event.target.value)}>{modes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field">Registration status<select name="status"><option>REGISTERING</option><option>ROOM READY</option><option>LIVE</option><option>COMPLETED</option></select></label><label className="field">Schedule<input required name="schedule" type="datetime-local" /></label><label className="field">Slot limit<input type="number" name="slots" required min="2" /></label><label className="field">Entry type<select name="entryType"><option>Free</option><option>Paid</option></select></label><label className="field">Entry fee<input name="entryFee" inputMode="decimal" placeholder="Set when applicable" /></label><label className="field">Prize pool<input name="prizePool" inputMode="decimal" placeholder="Set when applicable" /></label><label className="field">Rules<textarea name="rules" required placeholder="Published event rules" /></label>{mode === 'br' && <><label className="field">Participation<select name="participation"><option>Solo</option><option>Duo</option><option>Squad</option></select></label><label className="field">Match format<input required name="matchFormat" placeholder="Number of matches and map rotation" /></label></>}{mode === 'cs' && <><label className="field">Team format<input name="teamFormat" value="4v4" readOnly /></label><label className="field">Match format<select name="bestOf"><option>BO3</option><option>BO5</option></select></label></>}{mode === 'lone-wolf' && <><label className="field">Participation<select name="participation"><option>1v1</option><option>2v2</option></select></label><label className="field">Match format<input name="bracket" value="Single elimination" readOnly /></label></>}<button className="platform-button lg:col-span-2 disabled:opacity-60" type="submit" disabled={loading}>{loading ? 'Saving configuration…' : 'Save tournament configuration'}</button>{message && <p role="status" className="text-sm text-[#c6ff91] lg:col-span-2">{message}</p>}</form>; }

function RoomManager() { const [message, setMessage] = useState(''); return <section className="platform-card mt-6"><p className="platform-label">Room management</p><h2 className="mt-2 text-xl font-medium">Set custom room access</h2><p className="mt-3 text-sm leading-6 text-[#a7adb4]">Room details are released only to verified registrations after the configured unlock threshold, normally 15 minutes before a match.</p><form className="mt-5 grid gap-4 lg:grid-cols-2" onSubmit={event => { event.preventDefault(); setMessage('Room information was not saved. Secure tournament and registration services are required.'); }}><label className="field">Tournament reference<input name="tournament" required /></label><label className="field">Match time<input name="matchTime" type="datetime-local" required /></label><label className="field">Custom Room ID<input name="roomId" required /></label><label className="field">Room password<input name="password" type="password" required /></label><label className="field lg:col-span-2">Match instructions<textarea name="instructions" required /></label><button className="platform-button lg:col-span-2" type="submit">Prepare room access</button></form>{message && <p role="status" className="mt-4 text-sm text-[#c6ff91]">{message}</p>}</section>; }

function ResultsManager() { const [placement, setPlacement] = useState('0'); const [kills, setKills] = useState('0'); const [message, setMessage] = useState(''); const total = calculateBrTotal({ placementPoints: Number(placement) || 0, killPoints: Number(kills) || 0 }); return <section className="platform-card mt-6"><p className="platform-label">Results management</p><h2 className="mt-2 text-xl font-medium">Review a BR score</h2><p className="mt-3 text-sm leading-6 text-[#a7adb4]">This calculator prepares a total from admin-entered placement and kill points. Results, rankings, and rewards remain unpublished until verified by the backend.</p><form className="mt-5 grid gap-4 lg:grid-cols-2" onSubmit={async event => { event.preventDefault(); setMessage((await platformCommands.updateMatchResult()).message); }}><label className="field">Placement points<input value={placement} onChange={event => setPlacement(event.target.value)} inputMode="numeric" /></label><label className="field">Kill points<input value={kills} onChange={event => setKills(event.target.value)} inputMode="numeric" /></label><div className="rounded-lg border border-[#a6ff43]/25 bg-[#a6ff43]/10 p-4 lg:col-span-2"><p className="text-sm text-[#c6ff91]">Calculated total points</p><p className="mt-1 text-2xl font-medium">{total}</p></div><label className="field lg:col-span-2">Verified result note<textarea name="note" required placeholder="Placement, kills, source, and review decision" /></label><button className="platform-button lg:col-span-2" type="submit">Submit result for verification</button></form>{message && <p role="status" className="mt-4 text-sm text-[#c6ff91]">{message}</p>}</section>; }

function SystemPanel({ section }: { section: string }) { const lines = section === 'Games' ? games.map(game => `${game.name} · ${game.status}`) : section === 'Modes' ? modes.map(mode => `${mode.name} (${mode.short}) · ${mode.description}`) : section === 'Rank Systems' ? internalRanks.map(rank => `${rank} · assigned from verified participation and performance`) : section === 'Achievements' ? achievementDefinitions.map(([name, description]) => `${name} · ${description}`) : section === 'Rules' ? Object.entries(competitiveRules).flatMap(([type, rules]) => rules.map(rule => `${type.toUpperCase()} · ${rule}`)) : section === 'Scoring Systems' ? ['BR · placement points + kill points = total score', 'CS · series wins and round progression', 'Lone Wolf · elimination advancement'] : ['BR · Solo, Duo, Squad', 'CS · 4v4 team bracket, BO3 or BO5', 'Lone Wolf · 1v1 or 2v2 single elimination']; return <section className="platform-card mt-6"><p className="text-sm text-[#a7adb4]">These are configuration definitions, not live competitive records.</p><div className="mt-5 grid gap-3">{lines.map(line => <div className="rounded-md border border-white/8 bg-white/[.02] p-4 text-sm" key={line}>{line}</div>)}</div></section>; }

export function AdminScreen({ section = 'Dashboard', form, tournamentId }: { section?: string; form?: 'create' | 'edit'; tournamentId?: string }) {
  const [mobile, setMobile] = useState(false);
  const [session, setSession] = useState<AuthSession | undefined>(undefined);
  const lower = section.toLowerCase().replaceAll(' ', '-') as keyof typeof adminRows;
  useEffect(() => { let active = true; authAdapter.getSession().then(result => { if (active) setSession(result); }); return () => { active = false; }; }, []);
  if (session === undefined) return <RestrictedAdminAccess state="checking" />;
  if (!session) return <RestrictedAdminAccess state="signed-out" />;
  if (!authAdapter.canAccessAdmin(session)) return <RestrictedAdminAccess state="forbidden" />;
  return <div className="admin-app flex min-h-dvh bg-[#101216] text-[#e6e8eb]">
    <style>{`body:has(.admin-app)>header,body:has(.admin-app)>footer{display:none}`}</style>
    <Sidebar />
    {mobile && <><button className="fixed inset-0 z-30 bg-black/70 lg:hidden" aria-label="Close admin navigation" onClick={() => setMobile(false)} /><Sidebar mobile close={() => setMobile(false)} /></>}
    <main className="min-w-0 flex-1">
      <header className="flex min-h-16 items-center border-b border-white/8 bg-[#181a1f] px-5">
        <button onClick={() => setMobile(true)} className="rounded-md border border-white/15 px-3 py-2 text-sm lg:hidden" aria-label="Open admin navigation">Menu</button>
        <div className="ml-3"><p className="text-sm text-[#a7adb4]">MasterGaming Control</p><p className="text-xs text-[#c6ff91]">Authenticated {session.user.role} access</p></div>
      </header>
      <div className="mx-auto max-w-[1600px] px-5 py-7 sm:px-8">
        <aside className="mb-6 rounded-lg border border-[#a6ff43]/25 bg-[#a6ff43]/8 px-4 py-4 text-sm leading-6 text-[#c8ccd1]">Access is granted from the authenticated <span className="text-[#c6ff91]">{session.user.role}</span> account role. All administrative actions remain subject to server-side authorization and verified service responses.</aside>
        {form ? <><p className="platform-label">Tournament configuration</p><h1 className="mt-2 text-2xl font-medium">{form === 'create' ? 'Create tournament' : 'Edit tournament'}</h1><p className="mt-2 text-sm leading-6 text-[#a7adb4]">Tournament changes are saved to the authenticated admin database.</p><ConnectedTournamentForm tournamentId={tournamentId} /></> : section === 'Dashboard' ? <Dashboard /> : <section><p className="platform-label">Management</p><h1 className="mt-2 text-2xl font-medium">{section}</h1><p className="mt-2 text-sm leading-6 text-[#a7adb4]">{adminIdentity.displayName} is a workspace label only. Records and permission checks come from the authenticated admin account and verified backend data.</p>{systems.includes(section) ? <SystemPanel section={section} /> : ['Matches', 'Results'].includes(section) ? <MatchManagement /> : section === 'Tournaments' ? <TournamentList /> : ['Credits', 'Withdrawals', 'Rewards', 'Transactions'].includes(section) ? <FinanceManagement section={section as 'Credits' | 'Withdrawals' | 'Rewards' | 'Transactions'} /> : <Table type={lower in adminRows ? lower : 'tournaments'} />}</section>}
      </div>
    </main>
  </div>;
}
