'use client';
import { useState, type FormEvent } from 'react';
import type { TeamSignupBlock as TeamSignupBlockType } from '@/payload-types';

export function TeamSignup({ eyebrow, heading, body, paymentNote }: TeamSignupBlockType) {
  const [message, setMessage] = useState('');
  const playerHeading = heading === 'Put your squad on the list.' ? 'Put your name on the list.' : heading;
  const playerBody = body === 'Send your team entry for a Free Fire tournament. We will review the details and confirm paid entry manually by email.' ? 'Send your individual entry for a Free Fire tournament. We will review your details and confirm paid entry manually by email.' : body;
  const playerPaymentNote = paymentNote === 'Payment is confirmed manually. Submitting this form requests your team slot; it does not automatically place your team in a lobby.' ? 'Payment is confirmed manually. Submitting this form requests your player slot; it does not automatically place you in a lobby.' : paymentNote;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const email = String(form.get('email') ?? ''); if (!email || !form.get('playerName') || !form.get('tournament')) { setMessage('Add your name, email, and tournament to continue.'); return; } setMessage('Sending your player entry…'); try { const json_body = Object.fromEntries(form.entries()); const response = await fetch('/api/v1/kite-platform/contact-form/submit', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ email, subject: 'MasterGaming.pk tournament signup', text_body: `Tournament entry from ${json_body.playerName}`, json_body }) }); setMessage(response.ok ? 'Entry received. We will confirm your payment manually by email.' : 'Could not send your entry. Please try again.'); if (response.ok) event.currentTarget.reset(); } catch { setMessage('Could not send your entry. Please try again.'); } };
  return <section id="join" className="bg-black px-5 py-20 sm:px-8 md:py-32"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="reveal"><p className="kicker">{eyebrow ?? 'Player entry'}</p><h2 className="mt-5 display-title text-4xl sm:text-6xl">{playerHeading}</h2>{playerBody ? <p className="body-copy mt-5">{playerBody}</p> : null}{playerPaymentNote ? <p className="mt-8 border-l border-[#d3ff24] pl-4 text-sm leading-6 text-white/70">{playerPaymentNote}</p> : null}</div><form onSubmit={submit} className="dark-card reveal grid gap-4 p-5 sm:grid-cols-2 sm:p-7"><label className="field sm:col-span-2">Player name<input name="playerName" required placeholder="Your name" /></label><label className="field">Free Fire UID<input name="freeFireUid" required placeholder="Your in-game UID" /></label><label className="field">WhatsApp number<input name="whatsapp" required placeholder="For confirmation" /></label><label className="field sm:col-span-2">Email<input name="email" type="email" required placeholder="you@email.com" /></label><label className="field sm:col-span-2">Tournament<select name="tournament" required defaultValue=""><option value="" disabled>Select a tournament</option><option>Friday Night Knockout</option><option>Weekend Squad Clash</option><option>Pro League Qualifier</option></select></label><label className="field sm:col-span-2">Notes (optional)<textarea name="notes" placeholder="Add any details for the tournament desk" rows={3}/></label><button className="rounded-full bg-[#d3ff24] px-5 py-3.5 text-sm font-bold text-black transition-transform hover:-translate-y-0.5 active:scale-[.97] sm:col-span-2">Send player entry</button>{message ? <p aria-live="polite" className="text-sm text-white/60 sm:col-span-2">{message}</p> : null}</form></div></section>;
}
