import type { CollectionConfig } from 'payload';
import { applyWalletChange } from '@/services/wallet-ledger';

const account = (user: unknown) => user as { collection?: string; role?: string; id?: number } | null;
const isAdmin = (user: unknown) => account(user)?.collection === 'platform-users' && account(user)?.role === 'Admin';
const isPlayer = (user: unknown) => account(user)?.collection === 'platform-users' && account(user)?.role === 'Player';
const own = (req: { user?: unknown }) => ({ player: { equals: account(req.user)?.id } });
const money = { type: 'number' as const, required: true, min: 0.01 };

export const Wallets: CollectionConfig = { slug: 'wallets', admin: { useAsTitle: 'id', hideAPIURL: true }, access: { create: () => false, update: () => false, delete: () => false, read: ({ req }) => isAdmin(req.user) || (isPlayer(req.user) ? own(req) : false) }, fields: [{ name: 'player', type: 'relationship', relationTo: 'platform-users', required: true, unique: true }, { name: 'balance', type: 'number', required: true, defaultValue: 0, min: 0 }] };

export const WalletLedger: CollectionConfig = { slug: 'wallet-ledger', labels: { singular: 'Ledger entry', plural: 'Ledger entries' }, admin: { useAsTitle: 'id', hideAPIURL: true, defaultColumns: ['player', 'type', 'amount', 'balanceAfter', 'createdAt'] }, access: { create: () => false, update: () => false, delete: () => false, read: ({ req }) => isAdmin(req.user) || (isPlayer(req.user) ? own(req) : false) }, fields: [{ name: 'player', type: 'relationship', relationTo: 'platform-users', required: true }, { name: 'amount', type: 'number', required: true }, { name: 'type', type: 'select', required: true, options: ['DEPOSIT', 'TOURNAMENT_FEE', 'REWARD', 'WITHDRAWAL'] }, { name: 'balanceAfter', type: 'number', required: true }, { name: 'idempotencyKey', type: 'text', required: true, unique: true }, { name: 'approvedBy', type: 'relationship', relationTo: 'platform-users' }, { name: 'tournament', type: 'relationship', relationTo: 'tournaments' }, { name: 'note', type: 'textarea' }] };

export const DepositRequests: CollectionConfig = { slug: 'deposit-requests', admin: { useAsTitle: 'id', hideAPIURL: true }, access: { create: ({ req }) => isPlayer(req.user), read: ({ req }) => isAdmin(req.user) || (isPlayer(req.user) ? own(req) : false), update: ({ req }) => isAdmin(req.user), delete: () => false }, hooks: { beforeChange: [({ data, operation, req }) => { if (operation === 'create') { if (!isPlayer(req.user)) throw new Error('Player authentication is required.'); data.player = account(req.user)?.id; data.status = 'PENDING'; } return data; }], afterChange: [async ({ doc, previousDoc, req }) => { if (doc.status === 'APPROVED' && previousDoc?.status !== 'APPROVED') await applyWalletChange({ payload: req.payload, player: typeof doc.player === 'object' ? doc.player.id : doc.player, amount: Number(doc.amount), type: 'DEPOSIT', idempotencyKey: `deposit:${doc.id}`, admin: account(req.user)?.id, note: `Approved deposit request #${doc.id}` }); return doc; }] }, fields: [{ name: 'player', type: 'relationship', relationTo: 'platform-users', required: true, admin: { readOnly: true } }, { name: 'amount', ...money }, { name: 'paymentMethod', type: 'select', required: true, options: ['EasyPaisa', 'JazzCash', 'Bank Transfer'] }, { name: 'proofReference', type: 'textarea', required: true }, { name: 'status', type: 'select', required: true, defaultValue: 'PENDING', options: ['PENDING', 'APPROVED', 'REJECTED'] }, { name: 'reviewNote', type: 'textarea' }] };

export const WithdrawalRequests: CollectionConfig = { slug: 'withdrawal-requests', admin: { useAsTitle: 'id', hideAPIURL: true }, access: { create: ({ req }) => isPlayer(req.user), read: ({ req }) => isAdmin(req.user) || (isPlayer(req.user) ? own(req) : false), update: ({ req }) => isAdmin(req.user), delete: () => false }, hooks: { beforeChange: [({ data, operation, req }) => { if (operation === 'create') { if (!isPlayer(req.user)) throw new Error('Player authentication is required.'); data.player = account(req.user)?.id; data.status = 'PENDING'; } return data; }], afterChange: [async ({ doc, previousDoc, req }) => { if (doc.status === 'COMPLETED' && previousDoc?.status !== 'COMPLETED') await applyWalletChange({ payload: req.payload, player: typeof doc.player === 'object' ? doc.player.id : doc.player, amount: -Number(doc.amount), type: 'WITHDRAWAL', idempotencyKey: `withdrawal:${doc.id}`, admin: account(req.user)?.id, note: `Completed withdrawal request #${doc.id}` }); return doc; }] }, fields: [{ name: 'player', type: 'relationship', relationTo: 'platform-users', required: true, admin: { readOnly: true } }, { name: 'amount', ...money }, { name: 'payoutMethod', type: 'select', required: true, options: ['EasyPaisa', 'JazzCash', 'Bank Transfer'] }, { name: 'accountDetails', type: 'textarea', required: true }, { name: 'status', type: 'select', required: true, defaultValue: 'PENDING', options: ['PENDING', 'APPROVED', 'REJECTED', 'COMPLETED'] }, { name: 'reviewNote', type: 'textarea' }] };

export const RewardAwards: CollectionConfig = { slug: 'reward-awards', admin: { useAsTitle: 'id', hideAPIURL: true }, access: { create: ({ req }) => isAdmin(req.user), read: ({ req }) => isAdmin(req.user), update: () => false, delete: () => false }, hooks: { beforeChange: [({ data, req }) => { if (!isAdmin(req.user)) throw new Error('Admin authorization is required.'); data.awardedBy = account(req.user)?.id; return data; }], afterChange: [async ({ doc, req }) => { await applyWalletChange({ payload: req.payload, player: typeof doc.player === 'object' ? doc.player.id : doc.player, amount: Number(doc.amount), type: 'REWARD', idempotencyKey: `reward:${doc.id}`, admin: account(req.user)?.id, tournament: typeof doc.tournament === 'object' ? doc.tournament.id : doc.tournament, note: doc.note || `Tournament reward #${doc.id}` }); return doc; }] }, fields: [{ name: 'player', type: 'relationship', relationTo: 'platform-users', required: true }, { name: 'tournament', type: 'relationship', relationTo: 'tournaments', required: true }, { name: 'amount', ...money }, { name: 'note', type: 'textarea' }, { name: 'awardedBy', type: 'relationship', relationTo: 'platform-users', required: true, admin: { readOnly: true } }] };
