/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'platform-users': PlatformUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'platform-users': PlatformUser;
    pages: Page;
    tournaments: Tournament;
    'tournament-registrations': TournamentRegistration;
    wallets: Wallet;
    'wallet-ledger': WalletLedger;
    'deposit-requests': DepositRequest;
    'withdrawal-requests': WithdrawalRequest;
    'reward-awards': RewardAward;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'platform-users': PlatformUsersSelect<false> | PlatformUsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    'tournament-registrations': TournamentRegistrationsSelect<false> | TournamentRegistrationsSelect<true>;
    wallets: WalletsSelect<false> | WalletsSelect<true>;
    'wallet-ledger': WalletLedgerSelect<false> | WalletLedgerSelect<true>;
    'deposit-requests': DepositRequestsSelect<false> | DepositRequestsSelect<true>;
    'withdrawal-requests': WithdrawalRequestsSelect<false> | WithdrawalRequestsSelect<true>;
    'reward-awards': RewardAwardsSelect<false> | RewardAwardsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PlatformUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PlatformUserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username?: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-users".
 */
export interface PlatformUser {
  id: number;
  full_name: string;
  role: 'Admin' | 'Player';
  permissions?:
    | (
        | 'tournaments.manage'
        | 'players.manage'
        | 'registrations.manage'
        | 'rooms.manage'
        | 'results.manage'
        | 'finance.manage'
        | 'payments.review'
        | 'withdrawals.review'
        | 'wallet.manage'
        | 'settings.manage'
      )[]
    | null;
  free_fire_uid: string;
  in_game_name: string;
  mobile_number: string;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'platform-users';
}
/**
 * Create and manage the pages for your website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | HeroBlock
        | FeatureGridBlock
        | CtaBlock
        | TestimonialListBlock
        | FaqBlock
        | GalleryBlock
        | StatsBlock
        | LogoCloudBlock
        | RichTextBlock
        | ContactBlock
        | CollectionListBlock
        | AudioEmbedBlock
        | PeopleListBlock
        | RelatedItemsBlock
        | TournamentBoardBlock
        | RankingsTableBlock
        | TeamSignupBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImageUrl?: string | null;
    /**
     * Override the canonical URL. Leave empty to use this page’s own URL.
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noindex?: boolean | null;
    /**
     * Robots meta content, e.g. max-image-preview:large. The noindex switch above takes precedence.
     */
    robots?: string | null;
    /**
     * JSON-LD blocks served with this page, exactly as stored.
     */
    jsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  imageUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading?: string | null;
  subheading?: string | null;
  features?:
    | {
        title: string;
        description?: string | null;
        iconUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  body?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialListBlock".
 */
export interface TestimonialListBlock {
  heading?: string | null;
  testimonials?:
    | {
        quote: string;
        authorName: string;
        authorTitle?: string | null;
        avatarUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading?: string | null;
  images?:
    | {
        imageUrl: string;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  heading?: string | null;
  logos?:
    | {
        imageUrl: string;
        alt?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  heading?: string | null;
  body?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionListBlock".
 */
export interface CollectionListBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Slug of the content collection to list (e.g. posts). Must match a registered collection.
   */
  collection: string;
  limit?: number | null;
  /**
   * Restrict the grid to one topicCluster (leave empty to list all). A restricted grid never shows the facet bar.
   */
  filterByTag?: string | null;
  /**
   * Show the visitor facet bar (?tag= links). Ignored when filterByTag is set.
   */
  showTagFilter?: boolean | null;
  sortBy?: ('publishDate' | 'title') | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'collectionList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudioEmbedBlock".
 */
export interface AudioEmbedBlock {
  heading?: string | null;
  provider?: ('spotify' | 'apple' | 'youtube' | 'soundcloud' | 'generic') | null;
  /**
   * The provider embed/player URL (used as iframe src).
   */
  embedUrl: string;
  caption?: string | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'audioEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleListBlock".
 */
export interface PeopleListBlock {
  heading?: string | null;
  people?:
    | {
        name: string;
        role?: string | null;
        bioShort?: string | null;
        avatarUrl?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'peopleList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedItemsBlock".
 */
export interface RelatedItemsBlock {
  heading?: string | null;
  /**
   * Slug of the content collection to relate within. Must match a registered collection.
   */
  collection: string;
  /**
   * Slug of the reference item; related items share its topicCluster.
   */
  fromSlug: string;
  limit?: number | null;
  /**
   * Section background. Leave empty to use the block’s default surface.
   */
  background?: ('light' | 'muted' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedItems';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TournamentBoardBlock".
 */
export interface TournamentBoardBlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  tournaments?:
    | {
        name: string;
        status?: string | null;
        entryFee: string;
        prizePool: string;
        matchTime: string;
        squadFormat: string;
        registrationDeadline: string;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tournamentBoard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RankingsTableBlock".
 */
export interface RankingsTableBlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  teams?:
    | {
        rank: string;
        teamName: string;
        matches: string;
        points: string;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rankingsTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamSignupBlock".
 */
export interface TeamSignupBlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  paymentNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamSignup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  name: string;
  game: string;
  gameMode: string;
  format: string;
  schedule: string;
  entryFee: number;
  prizePool: number;
  maxSlots: number;
  registeredSlots: number;
  status: 'REGISTERING' | 'ROOM READY' | 'LIVE' | 'COMPLETED' | 'CANCELLED';
  entryType: 'Free' | 'Paid';
  rules: string;
  participation?: ('Solo' | 'Duo' | 'Squad') | null;
  /**
   * Room access is managed by Admin accounts only.
   */
  matchRoom?: {
    roomId?: string | null;
    roomPassword?: string | null;
    matchStartTime?: string | null;
    roomUnlockTime?: string | null;
    status?: ('Upcoming' | 'Room Ready' | 'Live' | 'Completed') | null;
  };
  createdBy: number | PlatformUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-registrations".
 */
export interface TournamentRegistration {
  id: number;
  tournament: number | Tournament;
  player: number | PlatformUser;
  status: 'REGISTERED' | 'CANCELLED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets".
 */
export interface Wallet {
  id: number;
  player: number | PlatformUser;
  balance: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallet-ledger".
 */
export interface WalletLedger {
  id: number;
  player: number | PlatformUser;
  amount: number;
  type: 'DEPOSIT' | 'TOURNAMENT_FEE' | 'REWARD' | 'WITHDRAWAL';
  balanceAfter: number;
  idempotencyKey: string;
  approvedBy?: (number | null) | PlatformUser;
  tournament?: (number | null) | Tournament;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deposit-requests".
 */
export interface DepositRequest {
  id: number;
  player: number | PlatformUser;
  amount: number;
  paymentMethod: 'EasyPaisa' | 'JazzCash' | 'Bank Transfer';
  proofReference: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  reviewNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawal-requests".
 */
export interface WithdrawalRequest {
  id: number;
  player: number | PlatformUser;
  amount: number;
  payoutMethod: 'EasyPaisa' | 'JazzCash' | 'Bank Transfer';
  accountDetails: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'COMPLETED';
  reviewNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-awards".
 */
export interface RewardAward {
  id: number;
  player: number | PlatformUser;
  tournament: number | Tournament;
  amount: number;
  note?: string | null;
  awardedBy: number | PlatformUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'platform-users';
        value: number | PlatformUser;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'tournament-registrations';
        value: number | TournamentRegistration;
      } | null)
    | ({
        relationTo: 'wallets';
        value: number | Wallet;
      } | null)
    | ({
        relationTo: 'wallet-ledger';
        value: number | WalletLedger;
      } | null)
    | ({
        relationTo: 'deposit-requests';
        value: number | DepositRequest;
      } | null)
    | ({
        relationTo: 'withdrawal-requests';
        value: number | WithdrawalRequest;
      } | null)
    | ({
        relationTo: 'reward-awards';
        value: number | RewardAward;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'platform-users';
        value: number | PlatformUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'platform-users';
        value: number | PlatformUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-users_select".
 */
export interface PlatformUsersSelect<T extends boolean = true> {
  full_name?: T;
  role?: T;
  permissions?: T;
  free_fire_uid?: T;
  in_game_name?: T;
  mobile_number?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        testimonialList?: T | TestimonialListBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        collectionList?: T | CollectionListBlockSelect<T>;
        audioEmbed?: T | AudioEmbedBlockSelect<T>;
        peopleList?: T | PeopleListBlockSelect<T>;
        relatedItems?: T | RelatedItemsBlockSelect<T>;
        tournamentBoard?: T | TournamentBoardBlockSelect<T>;
        rankingsTable?: T | RankingsTableBlockSelect<T>;
        teamSignup?: T | TeamSignupBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImageUrl?: T;
        canonicalUrl?: T;
        noindex?: T;
        robots?: T;
        jsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  imageUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        iconUrl?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialListBlock_select".
 */
export interface TestimonialListBlockSelect<T extends boolean = true> {
  heading?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorTitle?: T;
        avatarUrl?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  images?:
    | T
    | {
        imageUrl?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        imageUrl?: T;
        alt?: T;
        href?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  email?: T;
  phone?: T;
  address?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionListBlock_select".
 */
export interface CollectionListBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  collection?: T;
  limit?: T;
  filterByTag?: T;
  showTagFilter?: T;
  sortBy?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudioEmbedBlock_select".
 */
export interface AudioEmbedBlockSelect<T extends boolean = true> {
  heading?: T;
  provider?: T;
  embedUrl?: T;
  caption?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleListBlock_select".
 */
export interface PeopleListBlockSelect<T extends boolean = true> {
  heading?: T;
  people?:
    | T
    | {
        name?: T;
        role?: T;
        bioShort?: T;
        avatarUrl?: T;
        href?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedItemsBlock_select".
 */
export interface RelatedItemsBlockSelect<T extends boolean = true> {
  heading?: T;
  collection?: T;
  fromSlug?: T;
  limit?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TournamentBoardBlock_select".
 */
export interface TournamentBoardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  tournaments?:
    | T
    | {
        name?: T;
        status?: T;
        entryFee?: T;
        prizePool?: T;
        matchTime?: T;
        squadFormat?: T;
        registrationDeadline?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RankingsTableBlock_select".
 */
export interface RankingsTableBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  teams?:
    | T
    | {
        rank?: T;
        teamName?: T;
        matches?: T;
        points?: T;
        status?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamSignupBlock_select".
 */
export interface TeamSignupBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  paymentNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  name?: T;
  game?: T;
  gameMode?: T;
  format?: T;
  schedule?: T;
  entryFee?: T;
  prizePool?: T;
  maxSlots?: T;
  registeredSlots?: T;
  status?: T;
  entryType?: T;
  rules?: T;
  participation?: T;
  matchRoom?:
    | T
    | {
        roomId?: T;
        roomPassword?: T;
        matchStartTime?: T;
        roomUnlockTime?: T;
        status?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-registrations_select".
 */
export interface TournamentRegistrationsSelect<T extends boolean = true> {
  tournament?: T;
  player?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets_select".
 */
export interface WalletsSelect<T extends boolean = true> {
  player?: T;
  balance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallet-ledger_select".
 */
export interface WalletLedgerSelect<T extends boolean = true> {
  player?: T;
  amount?: T;
  type?: T;
  balanceAfter?: T;
  idempotencyKey?: T;
  approvedBy?: T;
  tournament?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deposit-requests_select".
 */
export interface DepositRequestsSelect<T extends boolean = true> {
  player?: T;
  amount?: T;
  paymentMethod?: T;
  proofReference?: T;
  status?: T;
  reviewNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "withdrawal-requests_select".
 */
export interface WithdrawalRequestsSelect<T extends boolean = true> {
  player?: T;
  amount?: T;
  payoutMethod?: T;
  accountDetails?: T;
  status?: T;
  reviewNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-awards_select".
 */
export interface RewardAwardsSelect<T extends boolean = true> {
  player?: T;
  tournament?: T;
  amount?: T;
  note?: T;
  awardedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  logoUrl?: string | null;
  colors?: {
    primary?: string | null;
    accent?: string | null;
  };
  fonts?: {
    heading?: string | null;
    body?: string | null;
    display?: string | null;
    mono?: string | null;
  };
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    tagline?: string | null;
    copyright?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  socialLinks?:
    | {
        platform: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Site-wide contact details, shown in the footer on every page.
   */
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImageUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  logoUrl?: T;
  colors?:
    | T
    | {
        primary?: T;
        accent?: T;
      };
  fonts?:
    | T
    | {
        heading?: T;
        body?: T;
        display?: T;
        mono?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        copyright?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImageUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}